#!/bin/bash

set -eu

PID=$1
SQL="select count(*) from information_schema.processlist where ID = $PID AND command = \"Query\""

COUNT=$(mysql -u "$USER" -e "$SQL" | sed -e '1d')

if [ "$COUNT" != 1 ]; then
    # おわった
    SQL3="select * from information_schema.processlist where ID = $PID"
    mysql -u "$USER" --table --execute "$SQL3"
fi
