#!/bin/bash

set -e

USEROPT=""

if test "$GITHUB_USER:$GITHUB_TOKEN" != ":"; then
    USEROPT="-u $GITHUB_USER:$GITHUB_TOKEN"
fi

CURL="curl -s"
GITHUB_CURL="$CURL $USEROPT"

if [ $# -ne 1 ]; then
    echo "nginx docker td-agent ansible packer peco hub jd proxysql boostnote redash rails mastodon puma gixy"
    exit
fi

case $1 in
    "nginx" ) echo "https://nginx.org/en/CHANGES";
	      $CURL http://nginx.org/en/CHANGES | grep Changes | head -n 10 ;;

    "docker" ) $CURL https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages | grep Version ;;

    "td-agent" ) echo "https://docs.treasuredata.com/articles/td-agent-changelog";
		 $CURL http://packages.treasuredata.com.s3.amazonaws.com/3/ubuntu/xenial/dists/xenial/contrib/binary-amd64/Packages | grep Version ;;

    "ansible") echo "https://github.com/ansible/ansible/blob/devel/CHANGELOG.md";
	       $GITHUB_CURL https://api.github.com/repos/ansible/ansible/tags | jq -r '.[].name' | head -n 10 ;;

    "packer") echo "https://github.com/hashicorp/packer/blob/master/CHANGELOG.md";
	      $GITHUB_CURL https://api.github.com/repos/hashicorp/packer/tags | jq -r '.[].name' | head -n 10 ;;

    "peco") $GITHUB_CURL https://api.github.com/repos/peco/peco/tags | jq -r '.[].name' | head -n 10 ;;

    "hub") $GITHUB_CURL https://api.github.com/repos/github/hub/tags | jq -r '.[].name' | head -n 10 ;;

    "jd") $GITHUB_CURL https://api.github.com/repos/tidwall/jd/tags | jq -r '.[].name' | head -n 10 ;;

    "proxysql") echo "https://github.com/sysown/proxysql/releases";
		$GITHUB_CURL https://api.github.com/repos/sysown/proxysql/tags | jq -r '.[].name' | head -n 10 ;;

    "boostnote") echo "https://github.com/BoostIO/boost-releases";
		 $GITHUB_CURL https://api.github.com/repos/BoostIO/Boostnote/tags | jq -r '.[].name' | head -n 10 ;;

    "redash") echo "https://github.com/getredash/redash/blob/master/CHANGELOG.md";
	       $GITHUB_CURL https://api.github.com/repos/getredash/redash/tags | jq -r '.[].name' | head -n 10 ;;

    "rails") echo "http://weblog.rubyonrails.org/";
	      $GITHUB_CURL https://api.github.com/repos/rails/rails/tags | jq -r '.[].name' | head -n 10 ;;

    "mastodon") echo "https://github.com/tootsuite/mastodon/releases";
	      $GITHUB_CURL https://api.github.com/repos/tootsuite/mastodon/tags | jq -r '.[].name' | head -n 10 ;;

    "puma") echo "https://github.com/puma/puma/blob/master/History.md";
	    $GITHUB_CURL https://api.github.com/repos/puma/puma/tags | jq -r '.[].name' | head -n 10 ;;

    "gixy") echo "https://github.com/yandex/gixy/releases";
	      $GITHUB_CURL https://api.github.com/repos/yandex/gixy/tags | jq -r '.[].name' | head -n 10 ;;

    *) echo "Not Found $1" >&2;;

esac
