#!/bin/bash

set -eu

if [ $# -ne 1 ]; then
    echo "set service"
    exit
fi

case $1 in
    "nginx" ) curl -s http://nginx.org/en/CHANGES | grep Changes | head -n 10 ;;
    "docker" ) curl -s https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages | grep Version ;;
    "td-agent" ) curl -s http://packages.treasuredata.com.s3.amazonaws.com/2/ubuntu/xenial/dists/xenial/contrib/binary-amd64/Packages | grep Version ;;
    "ansible") curl -s https://api.github.com/repos/ansible/ansible/tags | jq -r '.[].name' | head -n 10 ;;
    "packer") curl -s https://api.github.com/repos/mitchellh/packer/tags | jq -r '.[].name' | head -n 10 ;;
    "peco") curl -s https://api.github.com/repos/peco/peco/tags | jq -r '.[].name' | head -n 10 ;;

esac
