#!/bin/bash

set -eu

if [ $# -ne 1 ]; then
    echo "set service"
    exit
fi

case $1 in
    "nginx" ) curl -s http://nginx.org/en/CHANGES | grep Changes | head -n 10 ;;
    "docker" ) curl -s https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Packages | grep Version ;;
esac
