#!/usr/bin/env python3
import os
import sys
import argparse
import urllib.request
import urllib.parse

WEBHOOK_URL = os.environ.get('WEBHOOK_URL')
CHANNEL = os.environ.get('CHANNEL')


def main():
    args = define_parsers()

    text = ""

    if args.first_line != "":
        text += args.first_line + "\n"

    text += "```"
    text += sys.stdin.read()
    text += "```"

    post_data = {
        'channel': CHANNEL,
        'username': args.user,
        'text': text,
        'icon_emoji': ':ghost:'
    }

    post(post_data)


def post(body):
    encoded_post_data = urllib.parse.urlencode({"payload": body}).encode(encoding='ascii')
    urllib.request.urlopen(url=WEBHOOK_URL, data=encoded_post_data)


def varidation():
    if WEBHOOK_URL is None:
        print("Set WEBHOOK_URL environment variable")
        exit(1)

    if CHANNEL is None:
        print("Set CHANNEL variable")
        exit(1)


def define_parsers():
    parser = argparse.ArgumentParser(description='Post to slack simply',
                                     add_help=False)
    parser.add_argument('--help', action='help', help='help')

    parser.add_argument('-u', '--user', type=str, default="webhookbot",
                        help='Username')
    parser.add_argument('-l', "--first-line", type=str, default="",
                        help='Add first line')

    return parser.parse_args()


if __name__ == "__main__":
    varidation()
    exit(main())
