#!/bin/bash

set -eu

export AWS_SHARED_CREDENTIALS_FILE="$HOME/.aws/credentials"
export AWS_PROFILE=$1
AWS_CLI="/usr/local/bin/aws"
JQ="/usr/bin/jq"

ssh "$($AWS_CLI ec2 describe-instances --filter "Name=instance-state-name,Values=running" \
    | $JQ ".Reservations[].Instances[] | select(has(\"PublicIpAddress\")) | {InstanceId, InstanceName: (.Tags[] | select(.Key==\"Name\").Value), PublicIpAddress}" \
    | jq -r 'to_entries | [.[].value] | @csv' \
    | sed s/\"//g \
    | peco \
    | cut -f 3 -d,)" "${@:2}"
